apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arena-connect-api
  name: arena-connect-deployment
  namespace: arena-connect
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: arena-connect-api
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: arena-connect-api
    spec:
      containers:
      - image: registry.gitlab.com/btbtravis/arena-connect-bot:0.0.1
        env:
        - name: MIX_ENV
          value: "prod"
        imagePullPolicy: IfNotPresent
        name: phonix-api
        ports:
        - containerPort: 4000
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: arena-connect-gitlab
      restartPolicy: Always
