apiVersion: v1
kind: Service
metadata:
  labels:
    app: arena-connect-api
  name: arena-connect-service
  namespace: arena-connect
spec:
  ports:
  - name: arena-connect-http
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: arena-connect-api
  sessionAffinity: None
  type: NodePort
