apiVersion: v1
kind: Service
metadata:
  labels:
    app: arena-connect-api
  name: arena-connect-service
  namespace: default
spec:
  ports:
  - name: arena-connect-http
    port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: arena-connect-api
